#ifndef LOGGING_H
#define LOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logDB)
Q_DECLARE_LOGGING_CATEGORY(logAudit)
Q_DECLARE_LOGGING_CATEGORY(logMigration)
Q_DECLARE_LOGGING_CATEGORY(logApp)
Q_DECLARE_LOGGING_CATEGORY(logSQL)

#endif // LOGGING_H
