# Исходные файлы
set(SOURCES
        src/main.cpp
        src/database/databasemanager.cpp
        src/database/connectionpool.cpp
        src/database/submiterrortablemodel.cpp
        src/database/repositories/terminalrepository.cpp
        src/database/repositories/clientrepository.cpp
        src/database/repositories/simcardrepository.cpp
        src/database/repositories/documentrepository.cpp
        src/database/repositories/paymentrepository.cpp
        src/ui/mainwindow.cpp
        src/ui/views/dashboardview.cpp
        src/ui/views/chartpanel.cpp
        src/ui/panels/backuppanel.cpp
        src/ui/panels/maintenancepanel.cpp
        src/ui/dialogs/manufacturersform.cpp
        src/ui/dialogs/modelsform.cpp
        src/ui/dialogs/clientsform.cpp
        src/ui/dialogs/simcardsform.cpp
        src/ui/dialogs/terminalsform.cpp
        src/ui/dialogs/terminaleditform.cpp
        resources.qrc
        src/ui/dialogs/receiptform.cpp
        src/ui/dialogs/serialunitsdialog.cpp
        src/ui/dialogs/rentalform.cpp
        src/ui/dialogs/returnform.cpp
        src/ui/dialogs/statuschangeform.cpp
        src/ui/dialogs/archivedocumentsform.cpp
        src/ui/dialogs/paymentform.cpp
        src/ui/dialogs/terminalhistoryform.cpp
        src/ui/dialogs/bulkimportform.cpp
        src/ui/dialogs/auditlogform.cpp
        src/ui/dialogs/loginform.cpp
        src/ui/dialogs/expirynotificationsform.cpp
        src/ui/dialogs/batchstatusform.cpp
        src/ui/dialogs/usermanagementform.cpp
        src/ui/dialogs/reportsform.cpp
        src/ui/dialogs/globalsearchdialog.cpp
        src/ui/dialogs/terminalhistorypickerdialog.cpp
        src/ui/dialogs/freedevicesreportdialog.cpp
        src/ui/dialogs/clientrentalreportdialog.cpp
        src/ui/dialogs/updatesettingsdialog.cpp
        src/utils/reportexporter.cpp
        src/utils/validator.cpp
        src/utils/registration_ratelimiter.cpp
        src/utils/logging.cpp
        src/utils/circuitbreaker.cpp
        src/utils/barcodeparser.cpp
        src/utils/barcodescanner.cpp
        src/utils/serialscanner.cpp
        src/ops/backupmanager.cpp
        src/ops/backupworker.cpp
        src/ops/opslog.cpp
        src/ops/opsscheduler.cpp
        src/update/updatemanager.cpp
        src/ui/base/printservice.cpp
        src/ui/base/transactionguard.cpp
        src/ui/base/documentdialog.cpp
        src/ui/base/clientdocdialog.cpp
        src/ui/dialogs/receiptform_post.cpp
        src/ui/dialogs/receiptform_scan.cpp
        src/ui/dialogs/rentalform_post.cpp
        src/ui/dialogs/returnform_post.cpp
        src/ui/dialogs/statuschangeform_post.cpp
        src/ui/dialogs/paymentform_post.cpp
        src/services/documentnumbergenerator.cpp
        src/services/postactionlogger.cpp
        src/services/statuschangeservice.cpp
        src/services/simcardservice.cpp
        src/services/serialunitsservice.cpp
)

set(HEADERS
        src/models/terminal.h
        src/models/client.h
        src/models/simcard.h
        src/models/rentaldocument.h
        src/models/document.h
        src/database/databasemanager.h
        src/database/idatabasemanager.h
        src/database/connectionpool.h
        src/database/submiterrortablemodel.h
        src/database/repositories/terminalrepository.h
        src/database/repositories/clientrepository.h
        src/database/repositories/simcardrepository.h
        src/database/repositories/documentrepository.h
        src/database/repositories/paymentrepository.h
        src/ui/mainwindow.h
        src/ui/views/dashboardview.h
        src/ui/views/chartpanel.h
        src/ui/panels/backuppanel.h
        src/ui/panels/maintenancepanel.h
        src/ui/dialogs/manufacturersform.h
        src/ui/dialogs/modelsform.h
        src/ui/dialogs/clientsform.h
        src/ui/dialogs/simcardsform.h
        src/ui/dialogs/terminalsform.h
        src/ui/dialogs/terminaleditform.h
        src/ui/delegates/readonlydelegate.h
        src/ui/dialogs/receiptform.h
        src/ui/dialogs/serialunitsdialog.h
        src/ui/delegates/comboboxdelegate.h
        src/ui/delegates/comboboxmodel.h
        src/ui/delegates/CheckBoxDelegate.h
        src/ui/dialogs/rentalform.h
        src/ui/dialogs/returnform.h
        src/ui/dialogs/statuschangeform.h
        src/ui/dialogs/archivedocumentsform.h
        src/ui/dialogs/paymentform.h
        src/ui/dialogs/terminalhistoryform.h
        src/ui/dialogs/bulkimportform.h
        src/ui/dialogs/auditlogform.h
        src/ui/dialogs/loginform.h
        src/ui/dialogs/expirynotificationsform.h
        src/ui/dialogs/batchstatusform.h
        src/ui/dialogs/usermanagementform.h
        src/ui/dialogs/reportsform.h
        src/ui/dialogs/globalsearchdialog.h
        src/ui/dialogs/terminalhistorypickerdialog.h
        src/ui/dialogs/freedevicesreportdialog.h
        src/ui/dialogs/clientrentalreportdialog.h
        src/ui/dialogs/updatesettingsdialog.h
        src/ui/base/documentdialog.h
        src/ui/base/clientdocdialog.h
        src/ui/base/printservice.h
        src/ui/base/transactionguard.h
        src/services/documentnumbergenerator.h
        src/services/postactionlogger.h
        src/services/statuschangeservice.h
        src/services/simcardservice.h
        src/services/serialunitsservice.h
        src/utils/reportexporter.h
        src/utils/validator.h
        src/utils/registration_ratelimiter.h
        src/utils/logging.h
        src/utils/circuitbreaker.h
        src/utils/barcodeparser.h
        src/utils/serialscanner.h
        src/utils/barcodescanner.h
        src/utils/password_utils.h
        src/ops/backupmanager.h
        src/ops/backupworker.h
        src/ops/opslog.h
        src/ops/opsscheduler.h
        src/update/updatemanager.h
        src/update/version.h
)

set(UI_FILES
        src/ui/mainwindow.ui
        src/ui/dialogs/manufacturersform.ui
        src/ui/dialogs/modelsform.ui
        src/ui/dialogs/clientsform.ui
        src/ui/dialogs/simcardsform.ui
        src/ui/dialogs/terminalsform.ui
        src/ui/dialogs/terminaleditform.ui
        src/ui/dialogs/receiptform.ui
        src/ui/dialogs/serialunitsdialog.ui
        src/ui/dialogs/rentalform.ui
        src/ui/dialogs/returnform.ui
        src/ui/dialogs/statuschangeform.ui
        src/ui/dialogs/archivedocumentsform.ui
        src/ui/dialogs/paymentform.ui
        src/ui/dialogs/terminalhistoryform.ui
        src/ui/dialogs/bulkimportform.ui
        src/ui/dialogs/auditlogform.ui
        src/ui/dialogs/loginform.ui
        src/ui/dialogs/expirynotificationsform.ui
        src/ui/dialogs/batchstatusform.ui
        src/ui/dialogs/reportsform.ui
)
